[package]
name = "newport_cache"
version = "0.0.1"
authors = ["Colby <me@cobeh.com>"]
edition = "2018"

[dependencies]
newport_engine = { path = "../newport_engine", version = "0.0.1" }
newport_serde = { path = "../newport_serde", version = "0.0.1" }