[package]
name = "newport"
version = "0.1.0"
authors = ["Colby <me@cobeh.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/colbyhall/newport"

[workspace]
members = ["crates/*"]

[dependencies]
core   = { path = "crates/core" }
os     = { path = "crates/os" }
asset  = { path = "crates/asset" }
log    = { path = "crates/log" }
engine = { path = "crates/engine" }

# Serde sadly has to be included in the dependency list of every package that uses it
serde = { version = "*", features = ["derive"] }