[package]
name = "newport"
version = "0.1.0"
authors = ["Colby <me@cobeh.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/colbyhall/newport"

[workspace]
members = ["crates/*"]

[dependencies]
newport_core   = { path = "crates/newport_core" }
newport_os     = { path = "crates/newport_os" }
newport_asset  = { path = "crates/newport_asset" }
newport_log    = { path = "crates/newport_log" }
newport_engine = { path = "crates/newport_engine" }

# Serde sadly has to be included in the dependency list of every package that uses it
serde = { version = "*", features = ["derive"] }

[[example]]
name = "hello_world"
path = "examples/hello_world.rs"