[package]
name = "newport_engine"
version = "0.0.1"
authors = ["Colby <me@cobeh.com>"]
edition = "2018"

[dependencies]
newport_core  = { path = "../newport_core" }
newport_os    = { path = "../newport_os" }