[package]
name = "engine"
version = "0.1.0"
authors = ["Colby <me@cobeh.com>"]
edition = "2018"

[dependencies]
core  = { path = "../core" }
os    = { path = "../os" }
asset = { path = "../asset" }
log   = { path = "../log" }