[package]
name = "newport_gpu"
version = "0.1.0"
authors = ["Colby <me@cobeh.com>"]
edition = "2018"

[dependencies]
newport_core   = { path = "../newport_core" }
newport_engine = { path = "../newport_engine" }
newport_log    = { path = "../newport_log" }
newport_asset  = { path = "../newport_asset" }
newport_os     = { path = "../newport_os" }
newport_math   = { path = "../newport_math" }

ash  = { version = "0.32.0" }
bitflags = "1.2"

[features]
default = ["vulkan"]
vulkan  = []