[package]
name = "newport_gpu"
version = "0.0.1"
authors = ["Colby <me@cobeh.com>"]
edition = "2018"

[dependencies]
newport_core   = { path = "../newport_core", version = "0.0.1" }
newport_engine = { path = "../newport_engine", version = "0.0.1" }
newport_log    = { path = "../newport_log", version = "0.0.1" }
newport_asset  = { path = "../newport_asset", version = "0.0.1" }
newport_os     = { path = "../newport_os", version = "0.0.1" }
newport_math   = { path = "../newport_math", version = "0.0.1" }

ash  = "0.32.0"
bitflags = "1.2"

[features]
default = ["vulkan"]
vulkan  = []